name: Config Sources > LEGACY Settings can be pulled from multiple sources
steps:
  - step: I have a "public/index.html" file with the content {html}
    html: >-
      <!DOCTYPE html><html lang="en"><head></head><body><link
      rel="pre-1.0-signal" href="_pagefind" >

      <h1>Hello.</h1></body></html>
  - step: I have a "pagefind.json" file with the content {json}
    json: |-
      {
          "source": "public"
      }
  - macro: I run Pagefind with "--bundle-dir _out"
  - step: stdout should contain "Running Pagefind"
  - step: The file "public/_out/pagefind.js" should not be empty
