name: Result Scoring > Term similarity ranking can be configured
steps:
  - ref: ./background.toolproof.yml
  - step: I have a "public/similar-term/index.html" file with the content {html}
    html: >-
      <!DOCTYPE html><html lang="en"><head></head><body><p>This post talks about
      abcdef once</p></body></html>
  - step: I have a "public/dissimilar-term/index.html" file with the content {html}
    html: >-
      <!DOCTYPE html><html lang="en"><head></head><body><p>This post talks about
      abcdefghijklmnopqrstuv — twice! abcdefghijklmnopqrstuv</p></body></html>
  - macro: I run Pagefind
  - step: stdout should contain "Running Pagefind"
  - step: I serve the directory "public"
  - step: In my browser, I load "/"
  - step: In my browser, I evaluate {js}
    js: >-
      let pagefind = await import("/pagefind/pagefind.js");


      let search = await pagefind.search(`abcdef`);


      let data = await Promise.all(search.results.map(result => result.data()));

      document.querySelector('[data-result]').innerText = data.map(d =>
      d.url).join(', ');
  - step: In my browser, the console should be empty
  - step: In my browser, I evaluate {js}
    js: |-
      let val = await toolproof.querySelector("[data-result]");
      toolproof.assert_eq(val.innerHTML, `/similar-term/, /dissimilar-term/`);
  - step: In my browser, I evaluate {js}
    js: >-
      let pagefind = await import("/pagefind/pagefind.js");

      await pagefind.options({
          ranking: {
              termSimilarity: 0.0
          }
      });


      let search = await pagefind.search(`abcdef`);


      let data = await Promise.all(search.results.map(result => result.data()));

      document.querySelector('[data-result]').innerText = data.map(d =>
      d.url).join(', ');
  - step: In my browser, the console should be empty
  - step: In my browser, I evaluate {js}
    js: |-
      let val = await toolproof.querySelector("[data-result]");
      toolproof.assert_eq(val.innerHTML, `/dissimilar-term/, /similar-term/`);
