//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(unused_mut)]
use snowball::SnowballEnv;
use snowball::Among;

static A_0: &'static [Among<Context>; 3] = &[
    Among("col", -1, -1, None),
    Among("par", -1, -1, None),
    Among("tap", -1, -1, None),
];

static A_1: &'static [Among<Context>; 7] = &[
    Among("", -1, 7, None),
    Among("H", 0, 6, None),
    Among("He", 1, 4, None),
    Among("Hi", 1, 5, None),
    Among("I", 0, 1, None),
    Among("U", 0, 2, None),
    Among("Y", 0, 3, None),
];

static A_2: &'static [Among<Context>; 6] = &[
    Among("iqU", -1, 3, None),
    Among("abl", -1, 3, None),
    Among("I\u{00E8}r", -1, 4, None),
    Among("i\u{00E8}r", -1, 4, None),
    Among("eus", -1, 2, None),
    Among("iv", -1, 1, None),
];

static A_3: &'static [Among<Context>; 3] = &[
    Among("ic", -1, 2, None),
    Among("abil", -1, 1, None),
    Among("iv", -1, 3, None),
];

static A_4: &'static [Among<Context>; 43] = &[
    Among("iqUe", -1, 1, None),
    Among("atrice", -1, 2, None),
    Among("ance", -1, 1, None),
    Among("ence", -1, 5, None),
    Among("logie", -1, 3, None),
    Among("able", -1, 1, None),
    Among("isme", -1, 1, None),
    Among("euse", -1, 11, None),
    Among("iste", -1, 1, None),
    Among("ive", -1, 8, None),
    Among("if", -1, 8, None),
    Among("usion", -1, 4, None),
    Among("ation", -1, 2, None),
    Among("ution", -1, 4, None),
    Among("ateur", -1, 2, None),
    Among("iqUes", -1, 1, None),
    Among("atrices", -1, 2, None),
    Among("ances", -1, 1, None),
    Among("ences", -1, 5, None),
    Among("logies", -1, 3, None),
    Among("ables", -1, 1, None),
    Among("ismes", -1, 1, None),
    Among("euses", -1, 11, None),
    Among("istes", -1, 1, None),
    Among("ives", -1, 8, None),
    Among("ifs", -1, 8, None),
    Among("usions", -1, 4, None),
    Among("ations", -1, 2, None),
    Among("utions", -1, 4, None),
    Among("ateurs", -1, 2, None),
    Among("ments", -1, 15, None),
    Among("ements", 30, 6, None),
    Among("issements", 31, 12, None),
    Among("it\u{00E9}s", -1, 7, None),
    Among("ment", -1, 15, None),
    Among("ement", 34, 6, None),
    Among("issement", 35, 12, None),
    Among("amment", 34, 13, None),
    Among("emment", 34, 14, None),
    Among("aux", -1, 10, None),
    Among("eaux", 39, 9, None),
    Among("eux", -1, 1, None),
    Among("it\u{00E9}", -1, 7, None),
];

static A_5: &'static [Among<Context>; 35] = &[
    Among("ira", -1, 1, None),
    Among("ie", -1, 1, None),
    Among("isse", -1, 1, None),
    Among("issante", -1, 1, None),
    Among("i", -1, 1, None),
    Among("irai", 4, 1, None),
    Among("ir", -1, 1, None),
    Among("iras", -1, 1, None),
    Among("ies", -1, 1, None),
    Among("\u{00EE}mes", -1, 1, None),
    Among("isses", -1, 1, None),
    Among("issantes", -1, 1, None),
    Among("\u{00EE}tes", -1, 1, None),
    Among("is", -1, 1, None),
    Among("irais", 13, 1, None),
    Among("issais", 13, 1, None),
    Among("irions", -1, 1, None),
    Among("issions", -1, 1, None),
    Among("irons", -1, 1, None),
    Among("issons", -1, 1, None),
    Among("issants", -1, 1, None),
    Among("it", -1, 1, None),
    Among("irait", 21, 1, None),
    Among("issait", 21, 1, None),
    Among("issant", -1, 1, None),
    Among("iraIent", -1, 1, None),
    Among("issaIent", -1, 1, None),
    Among("irent", -1, 1, None),
    Among("issent", -1, 1, None),
    Among("iront", -1, 1, None),
    Among("\u{00EE}t", -1, 1, None),
    Among("iriez", -1, 1, None),
    Among("issiez", -1, 1, None),
    Among("irez", -1, 1, None),
    Among("issez", -1, 1, None),
];

static A_6: &'static [Among<Context>; 38] = &[
    Among("a", -1, 3, None),
    Among("era", 0, 2, None),
    Among("asse", -1, 3, None),
    Among("ante", -1, 3, None),
    Among("\u{00E9}e", -1, 2, None),
    Among("ai", -1, 3, None),
    Among("erai", 5, 2, None),
    Among("er", -1, 2, None),
    Among("as", -1, 3, None),
    Among("eras", 8, 2, None),
    Among("\u{00E2}mes", -1, 3, None),
    Among("asses", -1, 3, None),
    Among("antes", -1, 3, None),
    Among("\u{00E2}tes", -1, 3, None),
    Among("\u{00E9}es", -1, 2, None),
    Among("ais", -1, 3, None),
    Among("erais", 15, 2, None),
    Among("ions", -1, 1, None),
    Among("erions", 17, 2, None),
    Among("assions", 17, 3, None),
    Among("erons", -1, 2, None),
    Among("ants", -1, 3, None),
    Among("\u{00E9}s", -1, 2, None),
    Among("ait", -1, 3, None),
    Among("erait", 23, 2, None),
    Among("ant", -1, 3, None),
    Among("aIent", -1, 3, None),
    Among("eraIent", 26, 2, None),
    Among("\u{00E8}rent", -1, 2, None),
    Among("assent", -1, 3, None),
    Among("eront", -1, 2, None),
    Among("\u{00E2}t", -1, 3, None),
    Among("ez", -1, 2, None),
    Among("iez", 32, 2, None),
    Among("eriez", 33, 2, None),
    Among("assiez", 33, 3, None),
    Among("erez", 32, 2, None),
    Among("\u{00E9}", -1, 2, None),
];

static A_7: &'static [Among<Context>; 6] = &[
    Among("e", -1, 3, None),
    Among("I\u{00E8}re", 0, 2, None),
    Among("i\u{00E8}re", 0, 2, None),
    Among("ion", -1, 1, None),
    Among("Ier", -1, 2, None),
    Among("ier", -1, 2, None),
];

static A_8: &'static [Among<Context>; 5] = &[
    Among("ell", -1, -1, None),
    Among("eill", -1, -1, None),
    Among("enn", -1, -1, None),
    Among("onn", -1, -1, None),
    Among("ett", -1, -1, None),
];

static G_v: &'static [u8; 20] = &[17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 130, 103, 8, 5];

static G_keep_with_s: &'static [u8; 17] = &[1, 65, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128];

#[derive(Clone)]
struct Context {
    i_p2: i32,
    i_p1: i32,
    i_pV: i32,
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            'golab2: loop {
                let v_2 = env.cursor;
                'lab3: loop {
                    'lab4: loop {
                        let v_3 = env.cursor;
                        'lab5: loop {
                            if !env.in_grouping(G_v, 97, 251) {
                                break 'lab5;
                            }
                            env.bra = env.cursor;
                            'lab6: loop {
                                let v_4 = env.cursor;
                                'lab7: loop {
                                    if !env.eq_s(&"u") {
                                        break 'lab7;
                                    }
                                    env.ket = env.cursor;
                                    if !env.in_grouping(G_v, 97, 251) {
                                        break 'lab7;
                                    }
                                    if !env.slice_from("U") {
                                        return false;
                                    }
                                    break 'lab6;
                                }
                                env.cursor = v_4;
                                'lab8: loop {
                                    if !env.eq_s(&"i") {
                                        break 'lab8;
                                    }
                                    env.ket = env.cursor;
                                    if !env.in_grouping(G_v, 97, 251) {
                                        break 'lab8;
                                    }
                                    if !env.slice_from("I") {
                                        return false;
                                    }
                                    break 'lab6;
                                }
                                env.cursor = v_4;
                                if !env.eq_s(&"y") {
                                    break 'lab5;
                                }
                                env.ket = env.cursor;
                                if !env.slice_from("Y") {
                                    return false;
                                }
                                break 'lab6;
                            }
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        'lab9: loop {
                            env.bra = env.cursor;
                            if !env.eq_s(&"\u{00EB}") {
                                break 'lab9;
                            }
                            env.ket = env.cursor;
                            if !env.slice_from("He") {
                                return false;
                            }
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        'lab10: loop {
                            env.bra = env.cursor;
                            if !env.eq_s(&"\u{00EF}") {
                                break 'lab10;
                            }
                            env.ket = env.cursor;
                            if !env.slice_from("Hi") {
                                return false;
                            }
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        'lab11: loop {
                            env.bra = env.cursor;
                            if !env.eq_s(&"y") {
                                break 'lab11;
                            }
                            env.ket = env.cursor;
                            if !env.in_grouping(G_v, 97, 251) {
                                break 'lab11;
                            }
                            if !env.slice_from("Y") {
                                return false;
                            }
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        if !env.eq_s(&"q") {
                            break 'lab3;
                        }
                        env.bra = env.cursor;
                        if !env.eq_s(&"u") {
                            break 'lab3;
                        }
                        env.ket = env.cursor;
                        if !env.slice_from("U") {
                            return false;
                        }
                        break 'lab4;
                    }
                    env.cursor = v_2;
                    break 'golab2;
                }
                env.cursor = v_2;
                if env.cursor >= env.limit {
                    break 'lab1;
                }
                env.next_char();
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true;
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_pV = env.limit;
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab2;
                }
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab2;
                }
                if env.cursor >= env.limit {
                    break 'lab2;
                }
                env.next_char();
                break 'lab1;
            }
            env.cursor = v_2;
            'lab3: loop {
                if env.find_among(A_0, context) == 0 {
                    break 'lab3;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            if env.cursor >= env.limit {
                break 'lab0;
            }
            env.next_char();
            'golab4: loop {
                'lab5: loop {
                    if !env.in_grouping(G_v, 97, 251) {
                        break 'lab5;
                    }
                    break 'golab4;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
            }
            break 'lab1;
        }
        context.i_pV = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    let v_4 = env.cursor;
    'lab6: loop {
        'golab7: loop {
            'lab8: loop {
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab8;
                }
                break 'golab7;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        'golab9: loop {
            'lab10: loop {
                if !env.out_grouping(G_v, 97, 251) {
                    break 'lab10;
                }
                break 'golab9;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        'golab11: loop {
            'lab12: loop {
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab12;
                }
                break 'golab11;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        'golab13: loop {
            'lab14: loop {
                if !env.out_grouping(G_v, 97, 251) {
                    break 'lab14;
                }
                break 'golab13;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab6;
    }
    env.cursor = v_4;
    return true;
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_1, context);
            if among_var == 0 {
                break 'lab1;
            }
            env.ket = env.cursor;
            if among_var == 1 {
                if !env.slice_from("i") {
                    return false;
                }
            } else if among_var == 2 {
                if !env.slice_from("u") {
                    return false;
                }
            } else if among_var == 3 {
                if !env.slice_from("y") {
                    return false;
                }
            } else if among_var == 4 {
                if !env.slice_from("\u{00EB}") {
                    return false;
                }
            } else if among_var == 5 {
                if !env.slice_from("\u{00EF}") {
                    return false;
                }
            } else if among_var == 6 {
                if !env.slice_del() {
                    return false;
                }
            } else if among_var == 7 {
                if env.cursor >= env.limit {
                    break 'lab1;
                }
                env.next_char();
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true;
}

fn r_RV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !(context.i_pV <= env.cursor){
        return false;
    }
    return true;
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !(context.i_p1 <= env.cursor){
        return false;
    }
    return true;
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !(context.i_p2 <= env.cursor){
        return false;
    }
    return true;
}

fn r_standard_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_4, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if among_var == 1 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_del() {
            return false;
        }
    } else if among_var == 2 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_del() {
            return false;
        }
        let v_1 = env.limit - env.cursor;
        'lab0: loop {
            env.ket = env.cursor;
            if !env.eq_s_b(&"ic") {
                env.cursor = env.limit - v_1;
                break 'lab0;
            }
            env.bra = env.cursor;
            'lab1: loop {
                let v_2 = env.limit - env.cursor;
                'lab2: loop {
                    if !r_R2(env, context) {
                        break 'lab2;
                    }
                    if !env.slice_del() {
                        return false;
                    }
                    break 'lab1;
                }
                env.cursor = env.limit - v_2;
                if !env.slice_from("iqU") {
                    return false;
                }
                break 'lab1;
            }
            break 'lab0;
        }
    } else if among_var == 3 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_from("log") {
            return false;
        }
    } else if among_var == 4 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_from("u") {
            return false;
        }
    } else if among_var == 5 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_from("ent") {
            return false;
        }
    } else if among_var == 6 {
        if !r_RV(env, context) {
            return false;
        }
        if !env.slice_del() {
            return false;
        }
        let v_3 = env.limit - env.cursor;
        'lab3: loop {
            env.ket = env.cursor;
            among_var = env.find_among_b(A_2, context);
            if among_var == 0 {
                env.cursor = env.limit - v_3;
                break 'lab3;
            }
            env.bra = env.cursor;
            if among_var == 1 {
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_3;
                    break 'lab3;
                }
                if !env.slice_del() {
                    return false;
                }
                env.ket = env.cursor;
                if !env.eq_s_b(&"at") {
                    env.cursor = env.limit - v_3;
                    break 'lab3;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_3;
                    break 'lab3;
                }
                if !env.slice_del() {
                    return false;
                }
            } else if among_var == 2 {
                'lab4: loop {
                    let v_4 = env.limit - env.cursor;
                    'lab5: loop {
                        if !r_R2(env, context) {
                            break 'lab5;
                        }
                        if !env.slice_del() {
                            return false;
                        }
                        break 'lab4;
                    }
                    env.cursor = env.limit - v_4;
                    if !r_R1(env, context) {
                        env.cursor = env.limit - v_3;
                        break 'lab3;
                    }
                    if !env.slice_from("eux") {
                        return false;
                    }
                    break 'lab4;
                }
            } else if among_var == 3 {
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_3;
                    break 'lab3;
                }
                if !env.slice_del() {
                    return false;
                }
            } else if among_var == 4 {
                if !r_RV(env, context) {
                    env.cursor = env.limit - v_3;
                    break 'lab3;
                }
                if !env.slice_from("i") {
                    return false;
                }
            }
            break 'lab3;
        }
    } else if among_var == 7 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_del() {
            return false;
        }
        let v_5 = env.limit - env.cursor;
        'lab6: loop {
            env.ket = env.cursor;
            among_var = env.find_among_b(A_3, context);
            if among_var == 0 {
                env.cursor = env.limit - v_5;
                break 'lab6;
            }
            env.bra = env.cursor;
            if among_var == 1 {
                'lab7: loop {
                    let v_6 = env.limit - env.cursor;
                    'lab8: loop {
                        if !r_R2(env, context) {
                            break 'lab8;
                        }
                        if !env.slice_del() {
                            return false;
                        }
                        break 'lab7;
                    }
                    env.cursor = env.limit - v_6;
                    if !env.slice_from("abl") {
                        return false;
                    }
                    break 'lab7;
                }
            } else if among_var == 2 {
                'lab9: loop {
                    let v_7 = env.limit - env.cursor;
                    'lab10: loop {
                        if !r_R2(env, context) {
                            break 'lab10;
                        }
                        if !env.slice_del() {
                            return false;
                        }
                        break 'lab9;
                    }
                    env.cursor = env.limit - v_7;
                    if !env.slice_from("iqU") {
                        return false;
                    }
                    break 'lab9;
                }
            } else if among_var == 3 {
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_5;
                    break 'lab6;
                }
                if !env.slice_del() {
                    return false;
                }
            }
            break 'lab6;
        }
    } else if among_var == 8 {
        if !r_R2(env, context) {
            return false;
        }
        if !env.slice_del() {
            return false;
        }
        let v_8 = env.limit - env.cursor;
        'lab11: loop {
            env.ket = env.cursor;
            if !env.eq_s_b(&"at") {
                env.cursor = env.limit - v_8;
                break 'lab11;
            }
            env.bra = env.cursor;
            if !r_R2(env, context) {
                env.cursor = env.limit - v_8;
                break 'lab11;
            }
            if !env.slice_del() {
                return false;
            }
            env.ket = env.cursor;
            if !env.eq_s_b(&"ic") {
                env.cursor = env.limit - v_8;
                break 'lab11;
            }
            env.bra = env.cursor;
            'lab12: loop {
                let v_9 = env.limit - env.cursor;
                'lab13: loop {
                    if !r_R2(env, context) {
                        break 'lab13;
                    }
                    if !env.slice_del() {
                        return false;
                    }
                    break 'lab12;
                }
                env.cursor = env.limit - v_9;
                if !env.slice_from("iqU") {
                    return false;
                }
                break 'lab12;
            }
            break 'lab11;
        }
    } else if among_var == 9 {
        if !env.slice_from("eau") {
            return false;
        }
    } else if among_var == 10 {
        if !r_R1(env, context) {
            return false;
        }
        if !env.slice_from("al") {
            return false;
        }
    } else if among_var == 11 {
        'lab14: loop {
            let v_10 = env.limit - env.cursor;
            'lab15: loop {
                if !r_R2(env, context) {
                    break 'lab15;
                }
                if !env.slice_del() {
                    return false;
                }
                break 'lab14;
            }
            env.cursor = env.limit - v_10;
            if !r_R1(env, context) {
                return false;
            }
            if !env.slice_from("eux") {
                return false;
            }
            break 'lab14;
        }
    } else if among_var == 12 {
        if !r_R1(env, context) {
            return false;
        }
        if !env.out_grouping_b(G_v, 97, 251) {
            return false;
        }
        if !env.slice_del() {
            return false;
        }
    } else if among_var == 13 {
        if !r_RV(env, context) {
            return false;
        }
        if !env.slice_from("ant") {
            return false;
        }
        return false;
    } else if among_var == 14 {
        if !r_RV(env, context) {
            return false;
        }
        if !env.slice_from("ent") {
            return false;
        }
        return false;
    } else if among_var == 15 {
        let v_11 = env.limit - env.cursor;
        if !env.in_grouping_b(G_v, 97, 251) {
            return false;
        }
        if !r_RV(env, context) {
            return false;
        }
        env.cursor = env.limit - v_11;
        if !env.slice_del() {
            return false;
        }
        return false;
    }
    return true;
}

fn r_i_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    if env.find_among_b(A_5, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    let v_3 = env.limit - env.cursor;
    'lab0: loop {
        if !env.eq_s_b(&"H") {
            break 'lab0;
        }
        env.limit_backward = v_2;
        return false;
    }
    env.cursor = env.limit - v_3;
    if !env.out_grouping_b(G_v, 97, 251) {
        env.limit_backward = v_2;
        return false;
    }
    if !env.slice_del() {
        return false;
    }
    env.limit_backward = v_2;
    return true;
}

fn r_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_6, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    if among_var == 1 {
        if !r_R2(env, context) {
            env.limit_backward = v_2;
            return false;
        }
        if !env.slice_del() {
            return false;
        }
    } else if among_var == 2 {
        if !env.slice_del() {
            return false;
        }
    } else if among_var == 3 {
        if !env.slice_del() {
            return false;
        }
        let v_3 = env.limit - env.cursor;
        'lab0: loop {
            env.ket = env.cursor;
            if !env.eq_s_b(&"e") {
                env.cursor = env.limit - v_3;
                break 'lab0;
            }
            env.bra = env.cursor;
            if !env.slice_del() {
                return false;
            }
            break 'lab0;
        }
    }
    env.limit_backward = v_2;
    return true;
}

fn r_residual_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        env.ket = env.cursor;
        if !env.eq_s_b(&"s") {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.bra = env.cursor;
        let v_2 = env.limit - env.cursor;
        'lab1: loop {
            let v_3 = env.limit - env.cursor;
            'lab2: loop {
                if !env.eq_s_b(&"Hi") {
                    break 'lab2;
                }
                break 'lab1;
            }
            env.cursor = env.limit - v_3;
            if !env.out_grouping_b(G_keep_with_s, 97, 232) {
                env.cursor = env.limit - v_1;
                break 'lab0;
            }
            break 'lab1;
        }
        env.cursor = env.limit - v_2;
        if !env.slice_del() {
            return false;
        }
        break 'lab0;
    }
    if env.cursor < context.i_pV {
        return false;
    }
    let v_5 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_7, context);
    if among_var == 0 {
        env.limit_backward = v_5;
        return false;
    }
    env.bra = env.cursor;
    if among_var == 1 {
        if !r_R2(env, context) {
            env.limit_backward = v_5;
            return false;
        }
        'lab3: loop {
            let v_6 = env.limit - env.cursor;
            'lab4: loop {
                if !env.eq_s_b(&"s") {
                    break 'lab4;
                }
                break 'lab3;
            }
            env.cursor = env.limit - v_6;
            if !env.eq_s_b(&"t") {
                env.limit_backward = v_5;
                return false;
            }
            break 'lab3;
        }
        if !env.slice_del() {
            return false;
        }
    } else if among_var == 2 {
        if !env.slice_from("i") {
            return false;
        }
    } else if among_var == 3 {
        if !env.slice_del() {
            return false;
        }
    }
    env.limit_backward = v_5;
    return true;
}

fn r_un_double(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let v_1 = env.limit - env.cursor;
    if env.find_among_b(A_8, context) == 0 {
        return false;
    }
    env.cursor = env.limit - v_1;
    env.ket = env.cursor;
    if env.cursor <= env.limit_backward {
        return false;
    }
    env.previous_char();
    env.bra = env.cursor;
    if !env.slice_del() {
        return false;
    }
    return true;
}

fn r_un_accent(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut v_1 = 1;
    'replab0: loop{
        'lab1: for _ in 0..1 {
            if !env.out_grouping_b(G_v, 97, 251) {
                break 'lab1;
            }
            v_1 -= 1;
            continue 'replab0;
        }
        break 'replab0;
    }
    if v_1 > 0 {
        return false;
    }
    env.ket = env.cursor;
    'lab2: loop {
        let v_3 = env.limit - env.cursor;
        'lab3: loop {
            if !env.eq_s_b(&"\u{00E9}") {
                break 'lab3;
            }
            break 'lab2;
        }
        env.cursor = env.limit - v_3;
        if !env.eq_s_b(&"\u{00E8}") {
            return false;
        }
        break 'lab2;
    }
    env.bra = env.cursor;
    if !env.slice_from("e") {
        return false;
    }
    return true;
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p2: 0,
        i_p1: 0,
        i_pV: 0,
    };
    let v_1 = env.cursor;
    r_prelude(env, context);
    env.cursor = v_1;
    r_mark_regions(env, context);
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_3 = env.limit - env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_4 = env.limit - env.cursor;
            'lab2: loop {
                let v_5 = env.limit - env.cursor;
                'lab3: loop {
                    let v_6 = env.limit - env.cursor;
                    'lab4: loop {
                        if !r_standard_suffix(env, context) {
                            break 'lab4;
                        }
                        break 'lab3;
                    }
                    env.cursor = env.limit - v_6;
                    'lab5: loop {
                        if !r_i_verb_suffix(env, context) {
                            break 'lab5;
                        }
                        break 'lab3;
                    }
                    env.cursor = env.limit - v_6;
                    if !r_verb_suffix(env, context) {
                        break 'lab2;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_5;
                let v_7 = env.limit - env.cursor;
                'lab6: loop {
                    env.ket = env.cursor;
                    'lab7: loop {
                        let v_8 = env.limit - env.cursor;
                        'lab8: loop {
                            if !env.eq_s_b(&"Y") {
                                break 'lab8;
                            }
                            env.bra = env.cursor;
                            if !env.slice_from("i") {
                                return false;
                            }
                            break 'lab7;
                        }
                        env.cursor = env.limit - v_8;
                        if !env.eq_s_b(&"\u{00E7}") {
                            env.cursor = env.limit - v_7;
                            break 'lab6;
                        }
                        env.bra = env.cursor;
                        if !env.slice_from("c") {
                            return false;
                        }
                        break 'lab7;
                    }
                    break 'lab6;
                }
                break 'lab1;
            }
            env.cursor = env.limit - v_4;
            if !r_residual_suffix(env, context) {
                break 'lab0;
            }
            break 'lab1;
        }
        break 'lab0;
    }
    env.cursor = env.limit - v_3;
    let v_9 = env.limit - env.cursor;
    r_un_double(env, context);
    env.cursor = env.limit - v_9;
    let v_10 = env.limit - env.cursor;
    r_un_accent(env, context);
    env.cursor = env.limit - v_10;
    env.cursor = env.limit_backward;
    let v_11 = env.cursor;
    r_postlude(env, context);
    env.cursor = v_11;
    return true;
}
