name: Config Sources > Settings can be pulled from command-line flags
steps:
  - step: I have a "public/index.html" file with the content {html}
    html: >-
      <!DOCTYPE html><html
      lang="en"><head></head><body><h1>Hello.</h1></body></html>
  - step: I run "%pagefind_exec_path% --site public"
  - step: stdout should contain "Running Pagefind"
  - step: The file "public/pagefind/pagefind.js" should not be empty
