name: Config Sources > Settings can be pulled from environment variables
steps:
  - step: I have a "public/index.html" file with the content {html}
    html: >-
      <!DOCTYPE html><html
      lang="en"><head></head><body><h1>Hello.</h1></body></html>
  - step: I have the environment variable "PAGEFIND_SITE" set to "public"
  - macro: I run Pagefind
  - step: stdout should contain "Running Pagefind"
  - step: The file "public/pagefind/pagefind.js" should not be empty
