name: Filtering > Filtering to any of a set of values or another filter
steps:
  - ref: ./background.toolproof.yml
  - step: In my browser, I evaluate {js}
    js: |-
      await test(pagefind.search("Cat", {
          filters: {
              any: {
                  color: {
                      any: ["Black", "Orange"]
                  },
                  mood: "Angry"
              }
          }
      }));
  - step: In my browser, the console should be empty
  - step: In my browser, I evaluate {js}
    js: >-
      let val = await toolproof.querySelector("[data-results]");

      toolproof.assert_eq(val.innerHTML, `/ali/, /cheeka/, /smudge/, /theodore/,
      /treacle/`);
