name: Filtering > Filtering to any of a set of values and another filter
steps:
  - ref: ./background.toolproof.yml
  - step: In my browser, I evaluate {js}
    js: |-
      await test(pagefind.search("Cat", {
          filters: {
              color: {
                  any: ["Black", "Orange"]
              },
              mood: "Lazy"
          }
      }));
  - step: In my browser, the console should be empty
  - step: In my browser, I evaluate {js}
    js: |-
      let val = await toolproof.querySelector("[data-results]");
      toolproof.assert_eq(val.innerHTML, `/cheeka/, /treacle/`);
  - step: In my browser, I evaluate {js}
    js: |-
      await test(pagefind.search("Cat", {
          filters: {
              color: {
                  any: ["Black", "Orange"]
              },
              mood: "Zen"
          }
      }));
  - step: In my browser, the console should be empty
  - step: In my browser, I evaluate {js}
    js: |-
      let val = await toolproof.querySelector("[data-results]");
      toolproof.assert_eq(val.innerHTML, `/theodore/`);
